openapi: 3.0.3
info:
  title: Free API by Dignicate,
  description: Implemented with Ktor.
  version: 1.0.0
servers:
  - url: 'https://freeapi.dignicate.com'
paths:
  /automobile/v1/companies:
    get:
      description: ""
      parameters:
        - name: "limit"
          in: "query"
          required: false
          schema:
            type: "integer"
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Company"
components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: array
          items:
            $ref: "#/components/schemas/LocalizedString"
        country:
          type: array
          items:
            $ref: "#/components/schemas/LocalizedString"
        founded_year:
          type: integer
    LocalizedString:
      type: object
      properties:
        language:
          type: string
        value:
          type: string
